repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
-   repo: https://github.com/python-poetry/poetry
    rev: '8dbe41e'
    hooks:
    -   id: poetry-check
        args: ["--lock"]
    -   id: poetry-lock
    -   id: poetry-install
-   repo: https://github.com/aerickson/poetry
    rev: '17e7f54'
    hooks:
    -   id: poetry-install
    -   id: poetry-update
